### ISSUE TITLE
Rewrite the package with hooks inorder to support SSR frameworks

### ISSUE THREAD

**Issue by SkySingh04** [msaracevic/react-embed-gist#12]
The error we get when trying to use the package with SSR frameworks such as Nextjs is:

```
WebpackError: ReferenceError: self is not defined

  - main.js:2 
    [app]/[react-embed-gist]/main.js:2:223
```

Rewriting the package with hooks will ensure compatibility across all frameworks

**Comment by msaracevic** [comment]
Please don't open duplicate issues. 

Also there is guarantee that hooks will work to solve this issue.  Rewriting with hooks was suggested only because the code base is small and could use refresh and then in hooks it would be easier to check for `window` and `document` existing, but there is no guarantee it will magically work.

Also keep in mind, even with that extra additional checks, it still goes against the SSR / SSG principle of rendering on server, since on server you can't embed the gist without `window` and `document`, so it would be served to an actual browser which would then do the call to the Github, retrieve and render the content. I am not sure that proponents of SSR / SSG are ok with that approach.

DUPLICATE: https://github.com/msaracevic/react-embed-gist/issues/11
